language: php

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.6
          env: DEPS=lowest
        - php: 5.6
          env: DEPS=latest
        - php: 7.0
          env: DEPS=lowest
        - php: 7.0
          env: DEPS=latest
        - php: 7.1
          env: DEPS=lowest
        - php: 7.1
          env: DEPS=latest
        - php: 7.2
          env: DEPS=lowest
        - php: 7.2
          env: DEPS=latest

before_script:
    - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-lowest --prefer-stable ; fi
    - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi

script:
    - ./vendor/bin/phpunit
